services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    command: --mysql-native-password=ON --innodb_buffer_pool_size=1024M --init-file /opt/scripts/init_db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=<MYSQL_ROOT_PASSWORD>
    ports:
      - '3306:3306'
    volumes:
      - /opt/nbiot-server/scripts:/opt/scripts
      - /opt/nbiot-server/db_data:/var/lib/mysql
      
  vernemq:
    image: vernemq/vernemq:2.0.1
    container_name: vernemq
    restart: always
    ports:
      - "1883:1883"
      - "8888:8888"
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes

  api-server:
    image: ghcr.io/aswatisrl/coap-apiserver:latest
    container_name: api-server
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /opt/nbiot-server/logs-apiserver:/usr/src/app/logs
      - /opt/nbiot-server/config-apiserver:/usr/src/app/config

  coap-gateway:
    image: ghcr.io/aswatisrl/coap-gateway:latest
    container_name: coap-gateway
    restart: always
    ports:
      - 5683:5683/udp
    volumes:
      - /opt/nbiot-server/logs-gateway:/opt/coap_server/logs
      - /opt/nbiot-server/config-gateway:/opt/coap_server/config

  coap-frontend:
    image: ghcr.io/aswatisrl/coap-frontend:latest
    container_name: coap-frontend
    restart: always
    ports:
      - 80:80/tcp

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
      
  ntp:
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVER=pool.ntp.org