API.USERNAME=coap_gateway_user
API.PASSWORD=gaJk%!FWft4Q7=HE
API.HOST=api-server
API.PORT=8080
COAP.HOST=0.0.0.0
COAP.LOCAL_PORT=5683
COAP.REMOTE_PORT=5683
MQTT.CONN_STRING=tcp://vernemq:1883
MQTT.USERNAME=
MQTT.PASSWORD=
MQTT.QOS=1